### ISSUE TITLE
PDI: Reducing ingester memory usage

### ISSUE THREAD

**Issue by nickbp** [opstrace/opstrace#1040]
When lots of series are involved, Cortex ingesters are prone to using tons of memory for an [in-memory cache of recent series data](https://cortexmetrics.io/docs/blocks-storage/#the-write-path). When exercising tens of millions of series, this cache is so big that it can easily account for the majority of the cost of running a cluster, quickly going into tens or hundreds of gigs _per ingester_. Meanwhile there hasn't been any perceptible difference in query performance between queries that fit within the cached 2H block vs queries that don't fit, so it's unclear what benefit the cache provides vs regular TSDB disk access.

Investigate options for reducing or eliminating this cache to keep better control on resource usage. For example, could the in-memory cache be capped to a certain number of series, where older data is dropped from the cache automatically when the cap is reached? Or could it just be turned off entirely?

**Comment by nickbp** [comment]
`ingester_v2.go` uses a lot of settings from the [`tsdb` section of the cortex config](https://cortexmetrics.io/docs/configuration/configuration-file/#blocks_storage_config). Here are the default values as of when I'd last checked a few weeks ago (cross-reference with linked doc for basic descriptions or check [`ingester_v2.go`](https://github.com/cortexproject/cortex/blob/8e84b22/pkg/ingester/ingester_v2.go#L235) and [`config.go`](https://github.com/cortexproject/cortex/blob/926a691/pkg/storage/tsdb/config.go#122) to see how the settings are used:
```
blocks_storage:
  [...]
  tsdb:
    dir: /cortex/tsdb
    block_ranges_period:
    - 2h0m0s
    retention_period: 6h0m0s
    ship_interval: 1m0s
    ship_concurrency: 10
    head_compaction_interval: 1m0s
    head_compaction_concurrency: 5
    head_compaction_idle_timeout: 1h0m0s
    head_chunks_write_buffer_size_bytes: 4194304
    stripe_size: 16384
    wal_compression_enabled: true
    wal_segment_size_bytes: 134217728
    flush_blocks_on_shutdown: false
    close_idle_tsdb_timeout: 0s
    max_tsdb_opening_concurrency_on_startup: 10
    max_exemplars: 0
```
Some possibly relevant options:
- Could reduce `block_ranges_period` from 2h to 1h, but maybe there are implications to doing that. For example wouldn't be surprised if there were weird caveats around changing this on the fly.
- Could reduce `retention_period` from the current 6h to 3h or 2h30m? Or whatever `block_ranges_period`+1h or +30m looks like.
- If series are rolling over frequently, reducing `head_compaction_idle_timeout` sounds like it'd clean up the old series more quickly? But unclear if this is in-memory or on-disk.

There's a `max_series` setting in the ingester runtime limits config (maps to `MaxInMemorySeries` internally), but when this limit is reached, new series data is [refused entirely](https://github.com/cortexproject/cortex/blob/8e84b22/pkg/ingester/ingester_v2.go#L235) rather than exiring data from the in-memory cache.
