### ISSUE TITLE
K8s integration: Include resource utilization in default scrape configuration

### ISSUE THREAD

**Issue by nickbp** [opstrace/opstrace#1070]
The default scrape configuration provided by the K8s integration currently covers `/metrics` on the kubelets, but not `/metrics/cadvisor`, which contains useful resource utilization metrics like `container_cpu_usage_seconds_total`. It'd make sense to include this in the default scrape config.

So far, I've successfully scraped `/metrics/cadvisor` from a test onprem K3s cluster using the following addition:
```
    # Collection of per-node metrics
    - job_name: 'kubernetes-nodes-cadvisor'
      kubernetes_sd_configs:
      - role: node

      metrics_path: /metrics/cadvisor
      scheme: https
      # TLS config for getting list of nodes to scrape, not querying nodes themselves
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      authorization:
        credentials_file: /var/run/secrets/kubernetes.io/serviceaccount/token

      relabel_configs:
      - target_label: __scheme__
        replacement: https
      # Include node hostname
      - source_labels: [__meta_kubernetes_node_label_kubernetes_io_hostname]
        target_label: instance
      # Include job label for the nodes
      - source_labels: []
        target_label: job
        replacement: kubelet-cadvisor
      # Include integration ID for autodetection in opstrace
      - source_labels: []
        target_label: integration_id
        replacement: 968a63b5-2b49-4ed9-b81e-818209cac34e
```

Need to check the following:
- I've only tried the above configuration on a test onprem cluster running K3s (added a stock integration then manually edited the `opstrace-prometheus` ConfigMap). Since the endpoint is against the kubelets themselves, should check some other clusters (e.g. EKS, GKE) and verify that the `/metrics/cadvisor` endpoint is also available there.
- The [K8s docs](https://kubernetes.io/docs/concepts/cluster-administration/system-metrics/#metrics-in-kubernetes) also mention `/metrics/resource` and `/metrics/probes` endpoints. While we're looking at this, can also check whether those endpoints have anything interesting.

The resulting integration changes should include the following:
- Updated ConfigMap template used for the K8s metrics integration to include the additional scrape target(s) - and tested across a few cluster environments to check there aren't any platform-specific kubelet issues.
- Updated prebuilt dashboards (provided via integration) to take advantage of the additional metrics (e.g. cpu/mem usage)
