### ISSUE TITLE
opstrace instance config: does not error out for unexpected properties in `gcp`

### ISSUE THREAD

**Issue by jgehrcke** [opstrace/opstrace#1330]
I used
```
tenants:
  - default
  - fun
cert_issuer: letsencrypt-prod
gcp:
    node_count: 5
    machine_type: n1-standard-16
    zone_suffix: a
```

The `node_count` property under `gcp` is ignored, and the top-level `node_count` default is used.
