### ISSUE TITLE
E2E Pre-PoC: Single instance accepting data and showing dashboards

### ISSUE THREAD

**Issue by nickbp** [opstrace/opstrace#1460]
Get to a working K8s YAML configuration -- check that things can indeed be connected together

- [ClickHouse operator](https://github.com/Altinity/clickhouse-operator)
- [Jaeger operator](https://github.com/jaegertracing/jaeger-operator)
- [Operator object example](https://github.com/jaegertracing/jaeger-clickhouse/blob/main/guide-kubernetes.md)

Desired end-state:
- Have a series of K8s YAML files that work in terms of data getting stored successfully, validating that things work together:
    - Can send Jaeger/gRPC-format data to Jaeger
    - Data visible in Jaeger dashboard
    - ClickHouse using persistent storage/PVCs
- Skipping ClickHouse replication for now
- Skipping OTLP format support for now

**Comment by nickbp** [comment]
OK, got a step-by-step that exercises creating an `opstrace_controller` user for managing things, as well as a per-tenant DB and per-tenant user/grant that should only allow access to the matching DB.

Some caveats since this is ultimately just an MVP to check that things should work E2E (see also TODOs):
- It doesn't do any fancy password/secrets management yet
- Clickhouse instance doesn't have replication nor sharding enabled yet

BUT given that, the following steps basically work for getting a working "tenant" running a Jaeger UI that in turn is storing data against a per-tenant DB in a "global" ClickHouse instance, using the configured credentials for access to the DB.

Closing this issue since as of the following instructions we have an E2E example. The next step is porting this into the Controller: #1461

## Install ClickHouse Operator

The default operator yaml deploys to `kube-system`.

```
CLICKHOUSE_OPERATOR_VERSION=0.16.0
curl -o clickhouse-operator-install-bundle-$CLICKHOUSE_OPERATOR_VERSION.yaml -L https://raw.githubusercontent.com/Altinity/clickhouse-operator/${CLICKHOUSE_OPERATOR_VERSION}/deploy/operator/clickhouse-operator-install-bundle.yaml
kubectl apply -f clickhouse-operator-install-bundle-$CLICKHOUSE_OPERATOR_VERSION.yaml
```

```
customresourcedefinition.apiextensions.k8s.io/clickhouseinstallations.clickhouse.altinity.com created
customresourcedefinition.apiextensions.k8s.io/clickhouseinstallationtemplates.clickhouse.altinity.com created
customresourcedefinition.apiextensions.k8s.io/clickhouseoperatorconfigurations.clickhouse.altinity.com created
serviceaccount/clickhouse-operator created
clusterrole.rbac.authorization.k8s.io/clickhouse-operator-kube-system created
clusterrolebinding.rbac.authorization.k8s.io/clickhouse-operator-kube-system created
configmap/etc-clickhouse-operator-files created
configmap/etc-clickhouse-operator-confd-files created
configmap/etc-clickhouse-operator-configd-files created
configmap/etc-clickhouse-operator-templatesd-files created
configmap/etc-clickhouse-operator-usersd-files created
deployment.apps/clickhouse-operator created
service/clickhouse-operator-metrics created
```

Wait for `kube-system/clickhouse-operator-xxxxx-yyyyy` to deploy.

## Install Jaeger Operator

This example deploys to `kube-system` via `-n` param.

```
JAEGER_OPERATOR_NAMESPACE=kube-system
JAEGER_OPERATOR_VERSION=1.27.0
rm -rf jaeger-$JAEGER_OPERATOR_VERSION && mkdir -p jaeger-$JAEGER_OPERATOR_VERSION && cd jaeger-$JAEGER_OPERATOR_VERSION
curl -OL https://raw.githubusercontent.com/jaegertracing/jaeger-operator/v${JAEGER_OPERATOR_VERSION}/deploy/crds/jaegertracing.io_jaegers_crd.yaml
curl -OL https://raw.githubusercontent.com/jaegertracing/jaeger-operator/v${JAEGER_OPERATOR_VERSION}/deploy/service_account.yaml
curl -OL https://raw.githubusercontent.com/jaegertracing/jaeger-operator/v${JAEGER_OPERATOR_VERSION}/deploy/cluster_role.yaml
curl -OL https://raw.githubusercontent.com/jaegertracing/jaeger-operator/v${JAEGER_OPERATOR_VERSION}/deploy/cluster_role_binding.yaml
curl -OL https://raw.githubusercontent.com/jaegertracing/jaeger-operator/v${JAEGER_OPERATOR_VERSION}/deploy/operator.yaml
kubectl apply -f jaegertracing.io_jaegers_crd.yaml
kubectl apply -n $JAEGER_OPERATOR_NAMESPACE -f service_account.yaml
kubectl apply -f cluster_role.yaml
# replace "observability" with the operator's namespace
cat cluster_role_binding.yaml | sed "s/namespace: \"observability\"/namespace: \"$JAEGER_OPERATOR_NAMESPACE\"/" | kubectl apply -f -
# set WATCH_NAMESPACE envvar to empty string - we want to watch all namespaces
cat operator.yaml | yq -y 'del(.spec.template.spec.containers[0].env[0].valueFrom)' | yq -y '.spec.template.spec.containers[0].env[0].value=""' | kubectl apply -n $JAEGER_OPERATOR_NAMESPACE -f -
cd ..
```

```
customresourcedefinition.apiextensions.k8s.io/jaegers.jaegertracing.io created
serviceaccount/jaeger-operator created
clusterrole.rbac.authorization.k8s.io/jaeger-operator created
clusterrolebinding.rbac.authorization.k8s.io/jaeger-operator created
deployment.apps/jaeger-operator created
```

Wait for `kube-system/jaeger-operator-xxxxx-yyyyy` to deploy.

## Deploy global Clickhouse

Basic instance without storage nor replication, derived from [here](https://github.com/jaegertracing/jaeger-clickhouse/blob/main/guide-kubernetes.md).

If we want ClickHouse replication and we AREN'T using ClickHouse Keeper, will need a separate ZK instance via e.g. the [Zookeeper operator](https://github.com/pravega/zookeeper-operator).

```
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Namespace
metadata:
  name: clickhouse
---
apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseInstallation
metadata:
  name: basic
  namespace: clickhouse
spec:
  # reference: https://github.com/Altinity/clickhouse-operator/blob/master/deploy/dev/clickhouse-operator-install-yaml-template-01-section-crd-01-chi.yaml#L358
  configuration:
    clusters:
    - name: cluster1
      layout:
        shardsCount: 1
        replicasCount: 1
    settings:
      # Tidy up warnings about failing to listen on IPv6 endpoint
      listen_host: "0.0.0.0"
      # other ClickHouse settings can be added here, slash-delimited
      # reference: https://clickhouse.com/docs/en/operations/server-configuration-parameters/settings/
    users:
      opstrace_controller/password: opstrace_controller_password
      opstrace_controller/networks/ip:
      - "0.0.0.0/0" # TODO restrict to "host local, regexp opstrace-controller-.*\.kube-system\.svc\.cluster\.local"?
      # opstrace_controller can create other users and grant access to them
      opstrace_controller/access_management: "1"
  defaults:
    templates:
      # Replace default PUBLIC LoadBalancer service with an internal ClusterIP service.
      # We don't want ClickHouse accessible to the world!!
      serviceTemplate: service-template
      # Configure volumes for storage (/var/lib/clickhouse) and logs (/var/log/clickhouse-server)
      dataVolumeClaimTemplate: data-volume
      logVolumeClaimTemplate: logs-volume
      # Configure image version, and add capabilities to tidy up startup warnings
      podTemplate: pod-template
  templates:
    # reference: https://github.com/Altinity/clickhouse-operator/blob/master/docs/custom_resource_explained.md#spectemplatesservicetemplates
    serviceTemplates:
    - name: service-template
      # resulting service at: basic.clickhouse.svc.cluster.local
      generateName: "{chi}"
      spec:
        # Default is a public LoadBalancer, we don't want that!
        type: ClusterIP
        # Must be provided manually or else deployment fails
        ports:
        - name: http
          port: 8123
        - name: client
          port: 9000
    # reference: https://github.com/Altinity/clickhouse-operator/blob/master/docs/custom_resource_explained.md#spectemplatesvolumeclaimtemplates
    volumeClaimTemplates:
    - name: data-volume
      spec:
        storageClassName: gp2 # TODO pd-ssd
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
    - name: logs-volume
      spec:
        storageClassName: gp2 # TODO pd-ssd
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
    # reference: https://github.com/Altinity/clickhouse-operator/blob/master/docs/custom_resource_explained.md#spectemplatespodtemplates
    podTemplates:
    - name: pod-template
      spec:
        securityContext:
          # Required for startup when we specify securityContext in container
          fsGroup: 101 # clickhouse gid
        containers:
        - name: clickhouse
          # Default is "latest" tag
          image: yandex/clickhouse-server:21.10.2.15
          securityContext:
            # Trying to tidy up startup warnings about missing capabilities,
            # but doesn't seem to work according to container logs...
            capabilities:
              drop:
              - ALL
              add:
              - IPC_LOCK
              - SYS_NICE
            # Required for startup when we specify securityContext here
            runAsUser: 101 # clickhouse uid
            runAsGroup: 101 # clickhouse gid
EOF
```

Wait for `clickhouse/chi-basic-cluster1-0-0-0` to deploy. `chi` is short for **C**lick**H**ouse**I**nstallation.

If it doesn't deploy, then check `kubectl describe chi -n clickhouse basic` for any errors.

## Create Database and User for Jaeger 1

NOTES:
- dashes are NOT valid in the DB name
- we use an underscore to ensure that this DB doesn't conflict with system DBs (namely "default" and "system")
- delete database using `DROP DATABASE IF EXISTS $db`, get database list using `SHOW DATABASES`
- delete user using `DROP USER IF EXISTS $user`, get user list using `SHOW USERS`, get all ACLs using `SHOW ACCESS`
- only `opstrace_controller` has access to edit users/grants (via ClickHouse instance bootstrap config)

TODO controller: create per-tenant DBs automatically
```
DATABASE=tenant_jaeger1
kubectl exec -n clickhouse -c clickhouse statefulset/chi-basic-cluster1-0-0 -- clickhouse client -u opstrace_controller --password opstrace_controller_password -n -q "CREATE DATABASE IF NOT EXISTS $DATABASE ENGINE=Atomic; SHOW DATABASES"
```

TODO controller: create per-tenant users automatically
```
kubectl exec -n clickhouse -c clickhouse statefulset/chi-basic-cluster1-0-0 -- clickhouse client -u opstrace_controller --password opstrace_controller_password -n -q "CREATE USER IF NOT EXISTS $DATABASE IDENTIFIED WITH plaintext_password BY '${DATABASE}_password' HOST ANY DEFAULT DATABASE $DATABASE; GRANT SELECT, INSERT, ALTER, CREATE, DROP, TRUNCATE, OPTIMIZE, SHOW ON ${DATABASE}.* TO $DATABASE; SHOW ACCESS"
```

## Deploy per-tenant Jaeger 1

Basic all-in-one instance with single pod, derived from [this](https://github.com/jaegertracing/jaeger-clickhouse/blob/main/guide-kubernetes.md) but with heavy modification based on underlying docs (see `reference`s).

```
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Namespace
metadata:
  name: test-jaeger1
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jaeger-clickhouse
  namespace: test-jaeger1
data:
  # config for jaeger-clickhouse storage plugin
  # reference: https://github.com/jaegertracing/jaeger-clickhouse/blob/main/config.yaml
  config.yaml: |
    address: tcp://basic.clickhouse.svc.cluster.local:9000
    max_span_count: 10_000_000
    batch_write_size: 10_000
    batch_flush_interval: 5s
    # json or protobuf: guessing that protobuf is a bit faster/smaller
    encoding: protobuf
    username: tenant_jaeger1
    password: tenant_jaeger1_password
    database: tenant_jaeger1
    metrics_endpoint: localhost:9090
    # note: affects which sql init scripts are used
    replication: false
    # days of data retention, or 0 to disable. configured at table setup via init sql scripts
    # reference: https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/mergetree/#table_engine-mergetree-ttl
    ttl: 0
---
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
  namespace: test-jaeger1
spec:
  # strategy can be allInOne (default), production (separate pods), or streaming (separate pods + kafka)
  # for now we just use allInOne for each (per-tenant) instance
  # reference: https://www.jaegertracing.io/docs/1.27/operator/#allinone-default-strategy
  strategy: allInOne
  allInOne:
    # 1.27 released 2021-10-07
    image: jaegertracing/all-in-one:1.27
    # reference: https://www.jaegertracing.io/docs/1.27/cli/#jaeger-all-in-one-grpc-plugin
    #options:
    #  log-level: debug
  storage:
    type: grpc-plugin
    grpcPlugin:
      # 0.8.0 released 2021-10-01
      image: ghcr.io/jaegertracing/jaeger-clickhouse:0.8.0
    options:
      grpc-storage-plugin:
        binary: /plugin/jaeger-clickhouse
        configuration-file: /plugin-config/config.yaml
        #log-level: debug
  ingress:
    # TODO controller: manage ingress (and certs) ourselves, with TLS and auth proxy configured
    # we might be able to populate the needed labels here, but using the controller keeps label config in a single location
    enabled: false
  ui:
    options:
      # just an example, reference: https://www.jaegertracing.io/docs/1.27/frontend-ui/
      menu:
      - label: "Hello Opstrace"
        items:
        - label: "Docs"
          url: "https://opstrace.com/docs"
        - label: "Blog"
          url: "https://opstrace.com/blog"
  # other options reference, e.g. labels or resources:
  #   https://www.jaegertracing.io/docs/1.27/operator/#finer-grained-configuration
  volumeMounts:
  - name: plugin-config
    mountPath: /plugin-config
  volumes:
  - name: plugin-config
    configMap:
      name: jaeger-clickhouse
EOF
```

Wait for `test-jaeger1/jaeger-xxxxx-yyyyy` to deploy.

Access Jaeger UI via port-forward:

```
kubectl port-forward -n test-jaeger1 deployments/jaeger query
```
-> [Jaeger UI](http://127.0.0.1:16686), go to Search tab then select Service=`jaeger-query`
