### ISSUE TITLE
requiredDuringSchedulingIgnoredDuringExecution affinity configuration prevents deployment rollout

### ISSUE THREAD

**Issue by sreis** [opstrace/opstrace#291]
**Describe the bug**

Using the default configuration, deployments using `requiredDuringSchedulingIgnoredDuringExecution` to prevent scheduling two pods of the same deployment to the same node instance cannot roll out when an update is made.

For example, by default, a cluster is created with 3 nodes, and the Cortex distributor is deployed with 3 replicas. When the rollout initiates, Kubernetes creates a new Pod. The new Pod is never scheduled because it fails the affinity check. After all, all the nodes are already running a distributor. 

**To Reproduce**

```bash
kubectl -n cortex rollout distributor
```

**Expected behavior**

If we update the distributor deployment, I expect it to roll out the new deployment without adding new nodes.

**Comment by sreis** [comment]
A fix is replacing `requiredDuringSchedulingIgnoredDuringExecution` with `preferredDuringSchedulingIgnoredDuringExecution`.

For the distributor the affinity rule would be:
```yaml
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  name: distributor
              topologyKey: kubernetes.io/hostname
            weight: 1
```
