### ISSUE TITLE
Read cloudwatch/stackdriver exporter docs, get running locally

### ISSUE THREAD

**Issue by nickbp** [opstrace/opstrace#311]
https://github.com/prometheus/cloudwatch_exporter
https://github.com/prometheus-community/stackdriver_exporter

Get exporters running locally, try to get them to fetch real metrics from AWS/GCP. Don't worry about getting them sending metrics to a prometheus instance just yet.

**Comment by nickbp** [comment]
They've each got amd64 images on Docker Hub:
- https://registry.hub.docker.com/r/prom/cloudwatch-exporter (cloudwatch_exporter-0.10.0, yesterday)
- https://registry.hub.docker.com/r/prometheuscommunity/stackdriver-exporter (v0.11.0, 5 months ago)

**Comment by nickbp** [comment]
Started with cloudwatch exporter, it was pretty straightforward:

Example yaml from the README at https://github.com/prometheus/cloudwatch_exporter (see also their example.yml for a more verbose config)
```
---
region: us-west-2
metrics:
 - aws_namespace: AWS/ELB
   aws_metric_name: RequestCount
   aws_dimensions: [AvailabilityZone, LoadBalancerName]
   aws_dimension_select:
     LoadBalancerName: [myLB]
   aws_statistics: [Sum]
```

Then run
```
docker run \
  --env AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
  --env AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
  -p 9106:9106 \
  -v /local/path/to/cloudwatch.yaml:/config/config.yml \
  prom/cloudwatch-exporter:cloudwatch_exporter-0.10.0
```

Then connect to `http://127.0.0.1:9106/metrics` to hopefully see a couple prom-formatted metrics. If `cloudwatch_exporter_scrape_error` != `0.0` then check `docker run` logs for any errors.

Sample result:
```
# HELP aws_resource_info AWS information available for resource
# TYPE aws_resource_info gauge
# HELP cloudwatch_exporter_scrape_duration_seconds Time this CloudWatch scrape took, in seconds.
# TYPE cloudwatch_exporter_scrape_duration_seconds gauge
cloudwatch_exporter_scrape_duration_seconds 1.082205726
# HELP cloudwatch_exporter_scrape_error Non-zero if this scrape failed.
# TYPE cloudwatch_exporter_scrape_error gauge
cloudwatch_exporter_scrape_error 0.0
# HELP tagging_api_requests_total API requests made to the Resource Groups Tagging API
# TYPE tagging_api_requests_total counter
# HELP cloudwatch_requests_total API requests made to CloudWatch
# TYPE cloudwatch_requests_total counter
cloudwatch_requests_total{action="listMetrics",namespace="AWS/ELB",} 1.0
# HELP cloudwatch_requests_created API requests made to CloudWatch
# TYPE cloudwatch_requests_created gauge
cloudwatch_requests_created{action="listMetrics",namespace="AWS/ELB",} 1.611722704948E9
```

**Comment by nickbp** [comment]
Less trivial example using some buildkite metrics that I found in the cloudwatch dashboards:

Config:
```
---
region: us-west-2
metrics:
 - aws_namespace: Buildkite
   aws_metric_name: ScheduledJobsCount
   aws_dimensions: [Org, Queue]
   aws_statistics: [Sum]
 - aws_namespace: Buildkite
   aws_metric_name: RunningJobsCount
   aws_dimensions: [Org, Queue]
   aws_statistics: [Sum]
 - aws_namespace: Buildkite
   aws_metric_name: WaitingJobsCount
   aws_dimensions: [Org, Queue]
   aws_statistics: [Sum]
```

prom output:
```
# HELP tagging_api_requests_total API requests made to the Resource Groups Tagging API
# TYPE tagging_api_requests_total counter
# HELP buildkite_scheduled_jobs_count_sum CloudWatch metric Buildkite ScheduledJobsCount Dimensions: [Org, Queue] Statistic: Sum Unit: Count
# TYPE buildkite_scheduled_jobs_count_sum gauge
buildkite_scheduled_jobs_count_sum{job="buildkite",instance="",org="opstrace",queue="default",} 0.0 1611723120000
# HELP buildkite_running_jobs_count_sum CloudWatch metric Buildkite RunningJobsCount Dimensions: [Org, Queue] Statistic: Sum Unit: Count
# TYPE buildkite_running_jobs_count_sum gauge
buildkite_running_jobs_count_sum{job="buildkite",instance="",org="opstrace",queue="default",} 5.0 1611723120000
# HELP buildkite_waiting_jobs_count_sum CloudWatch metric Buildkite WaitingJobsCount Dimensions: [Org, Queue] Statistic: Sum Unit: Count
# TYPE buildkite_waiting_jobs_count_sum gauge
buildkite_waiting_jobs_count_sum{job="buildkite",instance="",org="opstrace",queue="default",} 5.0 1611723120000
# HELP aws_resource_info AWS information available for resource
# TYPE aws_resource_info gauge
# HELP cloudwatch_exporter_scrape_duration_seconds Time this CloudWatch scrape took, in seconds.
# TYPE cloudwatch_exporter_scrape_duration_seconds gauge
cloudwatch_exporter_scrape_duration_seconds 2.488451025
# HELP cloudwatch_exporter_scrape_error Non-zero if this scrape failed.
# TYPE cloudwatch_exporter_scrape_error gauge
cloudwatch_exporter_scrape_error 0.0
# HELP cloudwatch_requests_total API requests made to CloudWatch
# TYPE cloudwatch_requests_total counter
cloudwatch_requests_total{action="getMetricStatistics",namespace="Buildkite",} 3.0
cloudwatch_requests_total{action="listMetrics",namespace="Buildkite",} 3.0
# HELP cloudwatch_requests_created API requests made to CloudWatch
# TYPE cloudwatch_requests_created gauge
cloudwatch_requests_created{action="getMetricStatistics",namespace="Buildkite",} 1.611723825257E9
cloudwatch_requests_created{action="listMetrics",namespace="Buildkite",} 1.611723825074E9
```
