### ISSUE TITLE
DD API: set up local dev env with cortex and grafana for data sanity-checking via plotting

### ISSUE THREAD

**Issue by jgehrcke** [opstrace/opstrace#329]

**Comment by jgehrcke** [comment]
### 1) build and run local DD API translation layer

```
$ pwd
/home/jp/dev/opstrace/go
```

```
$ rm -f ddapi && \
  make build-ddapi && \
  ./ddapi -disable-api-authn -loglevel debug \
  -prom-remote-write-url http://127.0.0.1:33333/api/v1/push -tenantname fun
```

### 2) run local Cortex with custom config

```
$ docker run -it --net=host -v $(pwd):/cwd cortexproject/cortex:v1.6.0 -config.file=/cwd/cortex-dev-cfg.yaml
...
```

with this config:

```yaml
$ cat cortex-dev-cfg.yaml 
auth_enabled: false

server:
  http_listen_port: 33333

  # Configure the server to allow messages up to 100MB.
  grpc_server_max_recv_msg_size: 104857600
  grpc_server_max_send_msg_size: 104857600
  grpc_server_max_concurrent_streams: 1000

distributor:
  shard_by_all_labels: true
  pool:
    health_check_ingesters: true

ingester_client:
  grpc_client_config:
    # Configure the client to allow messages up to 100MB.
    max_recv_msg_size: 104857600
    max_send_msg_size: 104857600
    grpc_compression: gzip

ingester:
  # We want our ingesters to flush chunks at the same time to optimise
  # deduplication opportunities.
  spread_flushes: true
  chunk_age_jitter: 0

  walconfig:
    wal_enabled: true
    recover_from_wal: true
    wal_dir: /tmp/cortex/wal

  lifecycler:
    # The address to advertise for this ingester.  Will be autodiscovered by
    # looking up address on eth0 or en0; can be specified if this fails.
    address: 127.0.0.1

    # We want to start immediately and flush on shutdown.
    join_after: 0
    min_ready_duration: 0s
    final_sleep: 0s
    num_tokens: 512
    tokens_file_path: /tmp/cortex/wal/tokens

    # Use an in memory ring store, so we don't need to launch a Consul.
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1

# Use local storage - BoltDB for the index, and the filesystem
# for the chunks.
schema:
  configs:
    - from: 2019-07-29
      store: boltdb
      object_store: filesystem
      schema: v10
      index:
        prefix: index_
        period: 1w

storage:
  boltdb:
    directory: /tmp/cortex/index

  filesystem:
    directory: /tmp/cortex/chunks

  delete_store:
    store: boltdb

purger:
  object_store_type: filesystem
```

### 3) verify query API

With the above's Cortex config, the Prometheus query API is exposed via `http://127.0.0.1:33333/prometheus/api/v1/query` -- quick confirmation via curl:

```
$ curl -v http://127.0.0.1:33333/prometheus/api/v1/query
*   Trying 127.0.0.1:33333...
* Connected to 127.0.0.1 (127.0.0.1) port 33333 (#0)
> GET /prometheus/api/v1/query HTTP/1.1
> Host: 127.0.0.1:33333
> User-Agent: curl/7.69.1
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 400 Bad Request
...
```

The `/prometheus/..` is configured through the Cortex `prometheus-http-prefix` parameter which defaults to `prometheus`.

### 4) run local Grafana

configure local Cortex as data source

```
$ docker run -it -p 3000:3000 --net host grafana/grafana
...
```



Open http://localhost:3000/ and log in with `admin`/`admin`.

### 5) configure local Cortex as data source

Looks like this:

![Screenshot from 2021-02-04 18-10-23](https://user-images.githubusercontent.com/265630/106931225-a29be800-6716-11eb-9429-ebdb12f1d5e4.png)
