### ISSUE TITLE
upgrades: (cortex|dd|loki)-apis pods crash looping

### ISSUE THREAD

**Issue by sreis** [opstrace/opstrace#450]
**Describe the bug**

(cortex|dd|loki|opstrace)-apis pods crash looping with the following error

```
time="2021-03-05T19:22:41Z" level=error msg="API_AUTHTOKEN_VERIFICATION_PUBKEY_SET must not be empty. Exit."
```

`loki-api` spec of a crash looping pod:

```
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: loki-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: loki-api
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  k8s-app: loki-api
              topologyKey: kubernetes.io/hostname
            weight: 100
      containers:
      - args:
        - -listen=:8080
        - -tenantname=system
        - -loki-querier-url=http://querier.loki.svc.cluster.local:1080
        - -loki-distributor-url=http://distributor.loki.svc.cluster.local:1080
        env:
        - name: API_AUTHTOKEN_VERIFICATION_PUBKEY_SET
        image: opstrace/loki-api:b3c0c6cb64ad8d38e65e2a576a4f84c3e2d8981b
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /metrics
            port: 8080
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: loki-api
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /metrics
            port: 8080
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: loki-api
      serviceAccountName: loki-api
      terminationGracePeriodSeconds: 30
```

**To Reproduce**

Upgrade from `opstrace/controller:d7fc806b-dev` to `opstrace/controller:1a8998dfd-dev`.
